if(NOT DEFINED SDRCAL_ARCHIVE OR NOT EXISTS "${SDRCAL_ARCHIVE}")
    message(FATAL_ERROR "package archive is missing: ${SDRCAL_ARCHIVE}")
endif()
if(NOT DEFINED SDRCAL_AUDIT_ROOT)
    message(FATAL_ERROR "SDRCAL_AUDIT_ROOT is required")
endif()

file(REMOVE_RECURSE "${SDRCAL_AUDIT_ROOT}")
file(MAKE_DIRECTORY "${SDRCAL_AUDIT_ROOT}")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E tar xf "${SDRCAL_ARCHIVE}"
    WORKING_DIRECTORY "${SDRCAL_AUDIT_ROOT}"
    RESULT_VARIABLE extract_result
)
if(NOT extract_result EQUAL 0)
    message(FATAL_ERROR "package archive extraction failed: ${extract_result}")
endif()

file(GLOB_RECURSE archive_files LIST_DIRECTORIES false "${SDRCAL_AUDIT_ROOT}/*")
set(required_names LICENSE THIRD_PARTY_NOTICES.md sdrcal.spdx.json
    sdr-calibration-profile.schema.json "sdrcal${SDRCAL_EXECUTABLE_SUFFIX}")
if(SDRCAL_EXPECT_CAPTURE)
    list(APPEND required_names "sdrcal-capture${SDRCAL_EXECUTABLE_SUFFIX}")
endif()
if(SDRCAL_EXPECT_GUI)
    list(APPEND required_names "sdrcal-gui${SDRCAL_EXECUTABLE_SUFFIX}")
endif()
foreach(required_name IN LISTS required_names)
    set(found false)
    foreach(archive_file IN LISTS archive_files)
        get_filename_component(archive_name "${archive_file}" NAME)
        if(archive_name STREQUAL required_name)
            set(found true)
            break()
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "archive is missing required content: ${required_name}")
    endif()
endforeach()

if(NOT SDRCAL_EXPECT_GUI)
    foreach(forbidden_name sdrcal-gui sdrcal.desktop SDRCalibration.icns
            SDRCalibration.ico icon-manifest.json)
        foreach(archive_file IN LISTS archive_files)
            get_filename_component(archive_name "${archive_file}" NAME)
            if(archive_name STREQUAL forbidden_name OR
               archive_name STREQUAL "${forbidden_name}${SDRCAL_EXECUTABLE_SUFFIX}")
                message(FATAL_ERROR
                    "CLI-only archive contains forbidden GUI content: ${archive_file}")
            endif()
        endforeach()
    endforeach()
endif()
if(NOT SDRCAL_EXPECT_CAPTURE)
    foreach(archive_file IN LISTS archive_files)
        get_filename_component(archive_name "${archive_file}" NAME)
        if(archive_name STREQUAL "sdrcal-capture${SDRCAL_EXECUTABLE_SUFFIX}")
            message(FATAL_ERROR
                "archive unexpectedly contains the SoapySDR capture executable")
        endif()
    endforeach()
endif()

file(GLOB_RECURSE spdx_files "${SDRCAL_AUDIT_ROOT}/*/sdrcal.spdx.json")
list(LENGTH spdx_files spdx_count)
if(NOT spdx_count EQUAL 1)
    message(FATAL_ERROR "archive must contain exactly one SPDX inventory")
endif()
list(GET spdx_files 0 spdx_file)
file(READ "${spdx_file}" spdx)
string(JSON spdx_version ERROR_VARIABLE json_error GET "${spdx}" spdxVersion)
if(json_error OR NOT spdx_version STREQUAL "SPDX-2.3")
    message(FATAL_ERROR "archive SPDX inventory is invalid: ${json_error}")
endif()
string(FIND "${spdx}" "${CMAKE_BINARY_DIR}" build_path_offset)
if(NOT build_path_offset EQUAL -1)
    message(FATAL_ERROR "archive metadata leaks a build-tree path")
endif()

message(STATUS "Portable archive content audit passed: ${SDRCAL_ARCHIVE}")
